# Generated by Django 5.0 on 2026-02-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(blank=True, max_length=200)),
                (
                    "skills",
                    models.TextField(
                        blank=True, help_text="Comma separated list of skills"
                    ),
                ),
                (
                    "education",
                    models.TextField(
                        blank=True, help_text="Details about your education"
                    ),
                ),
                (
                    "work_experience",
                    models.TextField(
                        blank=True, help_text="Details about your work history"
                    ),
                ),
                ("linkedin_link", models.URLField(blank=True)),
                ("portfolio_link", models.URLField(blank=True)),
            ],
        ),
    ]
