# Generated by Django 5.0 on 2026-03-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_recruiter",
            field=models.BooleanField(
                default=False, help_text="Check this box if you are a recruiter"
            ),
        ),
    ]
