# Generated by Django 5.0 on 2026-03-11 03:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_savedsearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedsearch',
            name='name',
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
