# Generated by Django 5.0 on 2026-03-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_savedsearch_name_savedsearch_creation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedsearch',
            options={'verbose_name': 'Saved Search', 'verbose_name_plural': 'Saved Seaches'},
        ),
        migrations.AddField(
            model_name='profile',
            name='notif_check',
            field=models.BooleanField(default=False),
        ),
    ]
