# Generated by Django 6.0.3 on 2026-03-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_savedsearch_options_profile_notif_check'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedsearch',
            options={'verbose_name': 'Saved Search', 'verbose_name_plural': 'Saved Searches'},
        ),
        migrations.AddField(
            model_name='profile',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_time_on_site',
            field=models.FloatField(default=0.0, help_text='Accumulated seconds the user has spent on the site'),
        ),
    ]
