# Generated by Django 5.0 on 2026-02-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_location_lat_job_location_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location_lat',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
        migrations.AlterField(
            model_name='job',
            name='location_long',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
