# Generated by Django 5.0 on 2026-03-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_replace_location_with_address_city_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills_required',
            field=models.CharField(max_length=500),
        ),
    ]
