# Generated by Django 5.0 on 2026-03-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_alter_job_address_alter_job_skills_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="company_name",
            field=models.CharField(default="Unknown", max_length=200),
            preserve_default=False,
        ),
    ]
